CREATE DATABASE proyectoRTN

CREATE TABLE usuarios (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENTT PRIMARY KEY
    nombre_usuarios VARCHAR (400) NOT NULL, 
    email VARCHAR (400),
    password VARCHAR (400),
    fecha_nac DATETIME
);

CREATE TABLE reseñas (
    id INT (10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
    id_serie INT UNSIGNED NOT NULL,
    id_usuario INT UNSIGNED NOT NULL,
    texto VARCHAR (1000) NOT NULL, 
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    puntaje INT UNSIGNED NOT NULL
);